server:
  port: 9090
spring:
  profiles:
#    active: mysql
    active: mongodb
  jpa:
    show-sql: true
#  jackson:
#    serialization:
#      INDENT_OUTPUT: true

logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
