spring:
  # 数据库设置
  datasource:
    url: jdbc:mysql://192.168.0.1:3306/test?useSSL=false
    username: user
    password: pwd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#debug: true
#  jpa:
#                          properties:
#                            hibernate:
#                              hbm2ddl:
#                                auto: update
